{% set version = "0.5.1" %}

package:
  name: inflection
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/inflection/inflection-{{ version }}.tar.gz
  sha256: 1a29730d366e996aaacffb2f1f1cb9593dc38e2ddd30c91250c6dde09ea9b417

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - inflection

about:
  home: https://github.com/jpvanhal/inflection
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A port of Ruby on Rails inflector to Python
  dev_url: https://github.com/jpvanhal/inflection
  doc_url: https://inflection.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - abloemert
