travis:
  secure:
    BINSTAR_TOKEN: cxj9JUtNaeAHBgs32wLr4oD3EOx2tAfVR0DmMASqubQL+Ef8DTSM3XXwGwy57hAEOWEr2lEtc75Ffq8G93pFvyQf8Uu6s65YRw1o4Fsj2USLWoz5Q2NAdIkdRpWUpRtUGVm4l50KuVDz4Q/h5LmYGm4auEl5bbE8KOzXX0NDgGynckSJ1RZXWZSTynXTG+91fAD8FEkndPXyrsDNNCUXchPu0stXEqvbHpu/HhRA6AZnOrVNU8Z1+Df9IDRpAYEhPPlwqfih85LjCkvuFJwocyc18zoUTdilXBmUzhCqpXUBFDHZkQ1qejlvjYXkMqt4eP2oGoTI4XAGwDB1pDf11o2uDS0NLpc/LU1Lph4K3WXP8JEENsFNjqchQYYenfI+m6knxft+3aGPEeSRYJu9p0jM+ktXZ0RXAlcSiYaUVyhOvsM2NnhJOhvlT/mrWCwembR/L8dthHQGd6OGKW3CGWpCD5cBmiIAV/UZ32Mo7wjfSnihguiO3q1TpzHUGWGqUqJveCec52mGuC0PaeZXct3Dh0nbB5HXs4sQOGTlkX/lJjwPYxQP6tVA8FzxZH/rjP7VWDf1xo+q+aDtdzmaMHcwKf7BXBh87w/wulG6J+VVwrhYuts0fqYCg8FcM94gIuQeQMuSQZrz6qXLKvQZ2PqmPzMRVMl92rYhObzq17o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
